// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon-wrap': string;
  'iconWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
